security:
    password_hashers:
        App\Entity\User: 'plaintext'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\AprendeAIAuthenticator
            logout:
                path: app_logout
                target: app_login
            entry_point: App\Security\AprendeAIAuthenticator


    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/$, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10